services:
  swirrl:
    build:
      context: .
      dockerfile: Dockerfile
    image: swirrl-service:local
    environment:
      SWIRRL_CONFIG_DIR: /var/lib/swirrl/config
      SWIRRL_CACHE_DIR: /var/lib/swirrl/cache
    ports:
      - "8000:8000"
    volumes:
      - swirrl_config:/var/lib/swirrl/config
      - swirrl_cache:/var/lib/swirrl/cache
      - ./Workspace:/media
    restart: unless-stopped

volumes:
  swirrl_config:
  swirrl_cache:
