#!/usr/bin/env python3
"""Prez Template Generator.

Generates final HTML templates by combining layouts with color themes.
Creates 60 templates (10 designs × 6 colors) in the generated/ directory.
"""

from pathlib import Path

import yaml

# Paths
SCRIPT_DIR = Path(__file__).parent
LAYOUTS_DIR = SCRIPT_DIR / "layouts"
THEMES_FILE = SCRIPT_DIR / "themes.yaml"
OUTPUT_DIR = SCRIPT_DIR / "generated"
BASE_TEMPLATE = SCRIPT_DIR / "_base.jinja2"
MACROS_TEMPLATE = SCRIPT_DIR / "_macros.jinja2"

# Languages to generate (English only for clean migration)
LANGUAGES = ["en"]


def load_themes():
    """Load theme definitions from themes.yaml."""
    with open(THEMES_FILE, encoding="utf-8") as f:
        return yaml.safe_load(f)


def generate_css_variables(colors):
    """Generate CSS custom properties from color definitions."""
    css_vars = []
    for key, value in colors.items():
        css_vars.append(f"--{key.replace('_', '-')}: {value};")
    return "\n      ".join(css_vars)


def generate_template(design_name, color_name, colors, language):
    """Generate a single template file."""
    # Create CSS variables
    css_vars = generate_css_variables(colors)

    # Read layout file
    layout_path = LAYOUTS_DIR / f"{design_name}.jinja2"
    if not layout_path.exists():
        print(f"Warning: Layout file not found: {layout_path}")
        return None

    # Replace the style_css placeholder with actual CSS variables
    # The layout extends _base.jinja2 which has {{ style_css(template_name) }}
    # We need to inject the CSS variables into the layout

    # Create a simple template that includes the layout with CSS vars injected
    template_content = f"""{{# Auto-generated template: {design_name}_{color_name}.{language}.jinja2 #}}
{{# Design: {design_name} | Color: {color_name} | Language: {language} #}}
{{# Generated by generate_templates.py - DO NOT EDIT MANUALLY #}}

{{%- set template_name = '{design_name}_{color_name}' -%}}
{{%- set locale = '{language}' -%}}

{{# Define CSS variables for this theme #}}
{{%- macro style_css(name) -%}}
{css_vars}
{{%- endmacro -%}}

{{# Include the layout #}}
{{%- include 'layouts/{design_name}.jinja2' -%}}
"""

    return template_content


def main():
    """Main generation function."""
    print("=" * 60)
    print("Prez Template Generator")
    print("=" * 60)

    # Create output directory
    OUTPUT_DIR.mkdir(exist_ok=True)
    print(f"\nOutput directory: {OUTPUT_DIR}")

    # Load themes
    print(f"\nLoading themes from: {THEMES_FILE}")
    themes_data = load_themes()
    designs = themes_data.get("designs", {})

    if not designs:
        print("Error: No designs found in themes.yaml")
        return

    print(f"Found {len(designs)} designs")

    # Generate templates
    total_generated = 0
    total_expected = len(designs) * 6 * len(LANGUAGES)  # 10 designs × 6 colors × 3 languages

    for design_name, design_config in designs.items():
        print(f"\n{'-' * 60}")
        print(f"Processing design: {design_name}")
        print(f"  Description: {design_config.get('description', 'N/A')}")
        print(f"  Layout: {design_config.get('layout', 'N/A')}")

        colors_config = design_config.get("colors", {})

        for color_name, colors in colors_config.items():
            for language in LANGUAGES:
                # Generate template
                template_content = generate_template(design_name, color_name, colors, language)

                if template_content:
                    # Write to file
                    output_filename = f"{design_name}_{color_name}.{language}.jinja2"
                    output_path = OUTPUT_DIR / output_filename

                    with open(output_path, "w", encoding="utf-8") as f:
                        f.write(template_content)

                    total_generated += 1
                    print(f"  [OK] Generated: {output_filename}")

    # Summary
    print(f"\n{'=' * 60}")
    print("Generation complete!")
    print(f"  Total templates generated: {total_generated}/{total_expected}")
    print(f"  Output directory: {OUTPUT_DIR}")
    print(f"{'=' * 60}\n")

    # Create index file
    create_index_file(designs, total_generated)


def create_index_file(designs, total_count):
    """Create an index file listing all generated templates."""
    index_path = OUTPUT_DIR / "INDEX.md"

    with open(index_path, "w", encoding="utf-8") as f:
        f.write("# Generated Prez Templates\n\n")
        f.write(f"Total templates: {total_count}\n\n")
        f.write("## Designs\n\n")

        for design_name, design_config in designs.items():
            f.write(f"### {design_name.replace('_', ' ').title()}\n\n")
            f.write(f"**Description:** {design_config.get('description', 'N/A')}\n\n")
            f.write("**Color Variants:**\n")

            colors = design_config.get("colors", {})
            for color_name in colors:
                f.write(f"- {color_name.title()}\n")

            f.write("\n**Files:**\n")
            for color_name in colors:
                for lang in LANGUAGES:
                    filename = f"{design_name}_{color_name}.{lang}.jinja2"
                    f.write(f"- `{filename}`\n")

            f.write("\n")

        f.write("\n## Usage\n\n")
        f.write("These templates are auto-generated from:\n")
        f.write("- Base template: `_base.jinja2`\n")
        f.write("- Macros: `_macros.jinja2`\n")
        f.write("- Layouts: `layouts/*.jinja2`\n")
        f.write("- Themes: `themes.yaml`\n\n")
        f.write("To regenerate, run: `python generate_templates.py`\n")

    print(f"Created index file: {index_path}")


if __name__ == "__main__":
    main()
